export const projectData = [
  {
    id: crypto.randomUUID(),
    title: "Get your T-rex",
    link: "trex",
    tech: "Ruby on Rails, JavaScript, HTML, CSS, Stimulus, Bootstrap",
    images: ["rex1", "rex2", "rex3", "rex4"],
  },
  {
    id: crypto.randomUUID(),
    title: "Movie2Night",
    link: "movie",
    tech: "Ruby on Rails, JavaScript, HTML, CSS, Stimulus, Bootstrap",
    images: ["movie1", "movie2", "movie3", "movie4", "movie5", "movie6"],
  },
  {
    id: crypto.randomUUID(),
    title: "CabInn",
    link: "cabinn",
    tech: "Ruby on Rails, JavaScript, HTML, CSS",
    images: ["cab1", "cab2", "cab3", "cab4"],
  },
  {
    id: crypto.randomUUID(),
    title: "Drumkit",
    link: "drum",
    tech: "JavaScript, HTML and CSS",
    images: ["drum1"],
  },
  {
    id: crypto.randomUUID(),
    title: "Escape the Owl",
    link: "owl",
    tech: "JavaScript, HTML and CSS",
    images: ["Owl1", "Owl2", "Owl3", "Owl4"],
  },
  {
    id: crypto.randomUUID(),
    title: "Task List",
    link: "task",
    tech: "JavaScript, HTML and CSS",
    images: ["task1"],
  },
  {
    id: crypto.randomUUID(),
    title: "Esolperth",
    link: "esolperth",
    tech: "WordPress, CSS & SEO",
    images: ["esol1","esol2","esol3","esol4"],
  },
];
